<div class="banners">
    <div class="row">
        <div class="col-md-6">
            <div class="grid1">
                <a href="#">
                    <img src="http://myproj.ee:81/media/wysiwyg/slide-2.jpg" alt="" width="566" height="536">
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="grid2 col-md-margin">
                <a href="#">
                    <img src="http://myproj.ee:81/media/wysiwyg/sale.jpg" alt="" width="279" height="264">
                </a>
            </div>
            <div class="grid3">
                <a href="#">
                    <img src="http://myproj.ee:81/media/wysiwyg/slide-3.jpg" alt="" width="279" height="264">
                </a>
            </div>
        </div>
        <div class="col-md-3">
            <div class="grid4">
                <a href="#">
                    <img src="http://myproj.ee:81/media/wysiwyg/slide-2.jpg" alt="" width="279" height="536">
                </a>
            </div>
        </div>
    </div>
</div>
