<h4>Just Arrived</h4>
<?php
    $featuredProducts = $this->getProductItems();
    if (!$featuredProducts): ?>
    <?= "feat prod don't exist"; ?>
    <?php else: ?>
        <div class="slideshow-container">
            <ul class="products-grid products-grid--max-6-col last">
            <?php foreach ($featuredProducts as $product): ?>
                <li class="item last" style="max-width= 100px">
                    <a href="<?php $product->getProductUrl(); ?>" class="product-image"><img src="http://myproj.ee:81/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/w/b/wbk012t.jpg" alt="img of item"></a>
                    <span>Quick View</span>
                    <div class="product-info" style="min-height= 194px; max-width= 100px;">
                    <h2 class="product-name">
<a href="<?php $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a>
</h2>
<div class="ratings">
<div class="rating-box">
<div class="rating" style="width: 100%;"></div>
</div>
<span class="amount">
<?php echo $this->getReviewsSummaryHtml($product, 'short') ?>
</span>
</div>
<div class="price-box">
<span class="regular-price" id="product-price-406">
<?php echo $this->getPriceHtml(); ?>
</span>
</div>
<div class="button-row">
<div class="addToCart">
<a href="javascript:void(0)">
<i><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v4.5a.5.5 0 0 1-1 0V3a3 3 0 0 1 6 0v4.5a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2z"/>
<path fill-rule="evenodd" d="M3.405 6a.5.5 0 0 0-.498.45l-.912 6.9A1.5 1.5 0 0 0 3.488 15h9.024a1.5 1.5 0 0 0 1.493-1.65l-.913-6.9a.5.5 0 0 0-.497-.45h-9.19zm-1.493.35A1.5 1.5 0 0 1 3.405 5h9.19a1.5 1.5 0 0 1 1.493 1.35L15 13.252A2.5 2.5 0 0 1 12.512 16H3.488A2.5 2.5 0 0 1 1 13.251l.912-6.9z"/>
</svg>
</i>
<span>Add to Cart</span>
</a>
</div>
<div class="addToWishlist">
<a href="javascript:void(0)">
<i></i>
</a>
</div>
<div class="compare">
<a href="javascript:void(0)">
<i></i>
</a>
</div>
</div>
</li>
<?php endforeach; ?>
</ul>
</div>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif; ?>


