<h4>Featured Items</h4>

<?php //echo $this->getLayout()->createBlock('vsourz_catproduct/productslider')->setCategoryId('15')->setTemplate('vsourz/products/productslider.phtml')->setTitle('Product Slider')->setProductCount('12')->toHtml();?>
<?php
    $featuredProducts = $this->getProductItems();
    if (!$featuredProducts): ?>
    <?= "feat prod don't exist"; ?>
    <?php else: ?>
    <div class="slider">
            <ul class="list-inline slider__wrapper">
            <?php foreach ($featuredProducts as $product): ?>
                <li class="slider__item list-inline-item" style="max-width= 150px">
                  <div class="item-area"> 
                    <a href="<?php $product->getProductUrl(); ?>" class="product-image"><img src="http://myproj.ee:81/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/w/b/wbk012t.jpg" alt="img of item" height="100" width="100"></a>
                    <span>Quick View</span>
                    <div class="product-info" style="min-height= 194px; max-width= 100px;">
                        <h2 class="product-name">
                            <a href="<?php $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a>
                        </h2>
                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating" style="width: 100%;"></div>
                            </div>
                            <span class="amount">
                                <?php echo $this->getReviewsSummaryHtml($product, 'short') ?>
                            </span>
                        </div>
                        <div class="price-box">
                            <span class="regular-price" id="product-price-406">
                            <?php echo $this->getPriceHtml(); ?>
                            </span>
                        </div>
                        <div class="button-row">
                            <div class="addToCart">
                                <a href="javascript:void(0)">
                                    <i><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-handbag" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 1a2 2 0 0 0-2 2v4.5a.5.5 0 0 1-1 0V3a3 3 0 0 1 6 0v4.5a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2z"/>
                                        <path fill-rule="evenodd" d="M3.405 6a.5.5 0 0 0-.498.45l-.912 6.9A1.5 1.5 0 0 0 3.488 15h9.024a1.5 1.5 0 0 0 1.493-1.65l-.913-6.9a.5.5 0 0 0-.497-.45h-9.19zm-1.493.35A1.5 1.5 0 0 1 3.405 5h9.19a1.5 1.5 0 0 1 1.493 1.35L15 13.252A2.5 2.5 0 0 1 12.512 16H3.488A2.5 2.5 0 0 1 1 13.251l.912-6.9z"/>
                                        </svg>
                                    </i>
                                    <span>Add to Cart</span>
                                </a>
                            </div>
                            <div class="addToWishlist">
                                <a href="javascript:void(0)">
                                    <i></i>
                                </a>
                            </div>
                            <div class="compare">
                                <a href="javascript:void(0)">
                                    <i></i>
                                </a>
                            </div>
                        </div>
                      </div> 
                    </li>
                <?php endforeach; ?>
            </ul>
            <a class="slider__control slider__control_left" href="#" role="button"></a>
            <a class="slider__control slider__control_right slider__control_show" href="#" role="button"></a>
        </div>
<?php endif; ?>

<!-- <style>
    /*!
     * chiefSlider (https://itchief.ru/lessons/php/feedback-form-for-website)
     * Copyright 2018 Alexander Maltsev
     * Licensed under MIT (https://github.com/itchief/feedback-form/blob/master/LICENSE)
     */


    .slider {
      position: relative;
      overflow: hidden;
    }

    .slider__wrapper {
      display: flex;
      transition: transform 0.6s ease;
      max-height: 250px; 
    }

    .slider__item {
      flex: 0 0 25%;
      max-width: 25%;
    }

    .slider__control {
      position: absolute;
      top: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 40px;
      color: #fff;
      text-align: center;
      opacity: 0.5;
      height: 50px;
      transform: translateY(-50%);
      background: rgba(0, 0, 0, .5);
    }

    .slider__control:hover,
    .slider__control:focus {
      color: #fff;
      text-decoration: none;
      outline: 0;
      opacity: .9;
    }

    .slider__control_left {
      left: 0;
    }

    .slider__control_right {
      right: 0;
    }

    .slider__control::before {
      content: '';
      display: inline-block;
      width: 20px;
      height: 20px;
      background: transparent no-repeat center center;
      background-size: 100% 100%;
    }

    .slider__control_left::before {
      background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
    }

    .slider__control_right::before {
      background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E");
    }

  </style> -->
</head>
